import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../../styles/Home.module.css'
import axios from "axios";
import Link from 'next/link';

import Button from 'react-bootstrap/Button';
import Modal from 'react-bootstrap/Modal';

var qs = require('qs');

export default function Home() {
  const [favoris, setFavoris] = useState([])
  const [pokeDetails, setPokeDetails] = useState<Record<any, string>>({})


  const fetchFav = async () => {
    await axios.get("http://localhost:3000/favoris")
      .then((res) => {
        setFavoris(res.data)
        console.log(res.data)
      })
  }

  const removeFav = async (id:any) => {
    await axios.get("http://localhost:3000")
      .then((res) => {
        setFavoris(res.data.pokemon)
        console.log(res.data.pokemon)
      })
  }

  useEffect(() => {
    fetchFav()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])



  return (
    <div className={styles.container}>
      <Head>
        <title>Favoris</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container text-center mt-5 pt-5 ">
        <h1 className={styles.title + " my-5 pt-5"}>
          LES FAVORIS  - <Link href={"/"}>acceuil</Link> 
        </h1>

        <div className="row">
          {favoris.map((favori: any, index) => (
            // eslint-disable-next-line react/jsx-key
            <div className='col-4 px-3 my-4  ' key={index}>
              {/* <Link href={`/pokemons/${pokemon.name}`}> */}
                <div className="card p-5 cursor-pointer"  onClick={()=> {
                  removeFav(favori.name)
                }} >
                    <button className='btn btn-danger position-absolute top-0 right-0 '> remove </button>
                  <h3>{favori.name}</h3>
                  <div className='d-flex justify-center'>
                        <img src={favori.image} alt="poke img " className='w-100' />
                  </div>
                </div>

              {/* </Link> */}
            </div>
          ))}
        </div>


      </main>
    </div>
  )
}
